title: Site

tabs:

  # content tab
  links:
    label: Links
    icon: text

    sections:

      # draft categories
      drafts:
        headline: Draft categories
        type: pages
        status: draft
        templates: category

      # visible categories
      published:
        headline: Visible categories
        type: pages
        status: listed
        templates: category

  other:
    label: Other content
    icon: template

    sections:

      # unlisted content
      unlisted:
        headline: Unlisted pages
        type: pages
        status: unlisted

  settings:
    label: Bentobox settings
    icon: settings

    settings:
    type: fields

    fields:

      theme:
        width: 1/3
        label: Site theme
        type: select
        default: dark-sea
        options:
          amethyst: Amethyst
          candy: Candy
          dark-sea: Dark sea
          dark-space: Dark space
          glow-stick: Glow stick
          jade: Jade
          lakeshore: Lakeshore
          light-lunch: Light lunch
          minimal: Minimal
          minty: Minty
          pink-party: Pink party
          retro-neon: Retro neon
          sci-fi: Sci-fi
          spring: Spring
          strawberry: Strawberry
          summer-night: Summer night
          sunset: Sunset

      fontfamily:
        width: 1/3
        label: Font
        type: select
        default: system
        options:
          system: System default
          space_mono: Space Mono
          fira_mono: Fira Mono
          open_sans: Open Sans
          plex_mono: Plex Mono
          plex_sans: Plex Sans
          plex_serif: Plex Serif
          roboto_slab: Roboto Slab

      fontsize:
        width: 1/3
        label: Font size
        type: range
        step: 0.05
        min: 0.5
        max: 1.5
        default: 1.0
        after: rem