title: Site

tabs:

  # content tab
  links:
    label: Links
    icon: text

    sections:

      # draft categories
      drafts:
        headline: Draft categories
        type: pages
        status: draft
        templates: category

      # visible categories
      published:
        headline: Visible categories
        type: pages
        status: listed
        templates: category

  other:
    label: Other content
    icon: template

    sections:

      # unlisted content
      unlisted:
        headline: Unlisted pages
        type: pages
        status: unlisted

  settings:
    label: Bentobox settings
    icon: settings

    settings:
    type: fields

    fields:

      theme:
        width: 1/4
        label: Site theme
        type: select
        default: dark-sea
        options:
          amethyst: Amethyst
          candy: Candy
          dark-sea: Dark sea
          dark-space: Dark space
          glow-stick: Glow stick
          jade: Jade
          lakeshore: Lakeshore
          light-lunch: Light lunch
          minimal: Minimal
          minty: Minty
          pink-party: Pink party
          retro-neon: Retro neon
          sci-fi: Sci-fi
          spring: Spring
          strawberry: Strawberry
          summer-night: Summer night
          sunset: Sunset

      fontsize:
        width: 1/4
        label: Font size
        type: select
        default: Medium
        options:
          - value: '0.84rem'
            text: Extra small
          - value: '0.92rem'
            text: Small
          - value: '1.0rem'
            text: Medium
          - value: '1.08rem'
            text: Large
          - value: '1.16rem'
            text: Extra large